apiVersion: isovalent.com/v1
kind: IsovalentEgressGatewayPolicy
metadata:
  name: green-policy
  labels:
    egw: bgp-advertise
    advertise: bgp

spec:
  destinationCIDRs:
  - "0.0.0.0/0"
  excludedCIDRs:
  - "10.200.0.0/16"
  egressCIDRs:
  - "192.150.9.124/31"

  egressGroups:
  - nodeSelector:
      matchLabels:
        node.kubernetes.io/name: cluster00-wkr00

  # selectors:
  # - namespaceSelector:
  #     matchExpressions:
  #     - key: kubernetes.io/metadata.name
  #       operator: In
  #       values:
  #       - blue
  #       - red
  #       - orange