apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      egress-node: "green"
  bgpInstances:
  - name: "instance-65010"
    localASN: 65010
    peers:
    - name: "r99"
      peerASN: 65005
      peerAddress: 10.0.0.99
      peerConfigRef:
        name: "cilium-peer"

    - name: "r03"
      peerASN: 65003
      peerAddress: 10.10.11.1
      peerConfigRef:
        name: "cilium-peer"

