
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: green-egress
spec:
  nodeSelector:
    matchLabels:
      egress-node: "green"
      #kubernetes.io/hostname: cluster00-wkr00
  virtualRouters:
  - localASN: 65010
    egressGatewayPolicySelector:
      matchLabels:
        advertise: bgp-green
    neighbors:
    - peerAddress: '10.0.0.99/32'
      eBGPMultihopTTL: 5
      peerASN: 65005
      families:
       - afi: ipv4
         safi: unicast
      advertisedPathAttributes:
      - selectorType: IsovalentEgressGatewayPolicy
        selector:
          matchLabels:
            advertise: bgp-green
