apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.10.10.2:6443
    token: "kzqvlw.y8i4hd21y2vo3cbp"
    caCertHashes:
    - "sha256:e8e59441bbc553ada2f13da578384d2cc4f2131ae834e442c71dc5bd1ea54bc2 "
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.10.10.101"