apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.10.10.2:6443
    token: "19wnlt.gteeew9zcl1afbhd"
    caCertHashes:
    - "sha256:1452402eb188549bab1e5893fa98ecb009acdd406e0a21e598bfd30efb8d4c7b"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.10.13.2"