apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.10.10.2:6443
    token: "kepki8.la9r0rt22cxcywy0"
    caCertHashes:
    - "sha256:94969b068e6e2cd66b9fc7235d2953c465fdd309ae6d5cba881a9fb5df53b717"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.10.10.104"