apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.10.10.2:6443
    token: "o5t2hy.vgrffujw35qr9ux0"
    caCertHashes:
    - "sha256:53821cbe3a800de81af09d747f0f0416acacb62bc74de98aa75875fa8c12db36"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.10.10.105"