apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.10.10.2:6443
    token: "7vfpei.av4yf5vuzigrcbes"
    caCertHashes:
    - "sha256:fb8f42679747e8d7f4717a977db4c6e1b940d47ae7be6059c57756c361275630"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.10.12.2,fc00:0:1002::2"