apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.10.10.2:6443
    token: "kkfynu.ft0ujbw0h9eikwpf"
    caCertHashes:
    - "sha256:05740bb3df5f9092ed606209d72728722e4d7942fae6711b126df35843171057"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.10.10.104"