network:
  ethernets:
    ens3:
      dhcp4: false
      addresses:
        - 192.168.122.103/24
    ens4:
      addresses:
        - 10.10.10.103/24
        - fc00:0:1000::103/64
      nameservers:
        addresses: [8.8.8.8]
    ens5:
      addresses:
        - 10.10.21.2/24
      routes:
        - to: default
          via: 10.10.21.1
  version: 2