apiVersion: isovalent.com/v1
kind: IsovalentEgressGatewayPolicy
metadata:
  name: green-policy
  labels:
    advertise: bgp

spec:
  destinationCIDRs:
  - "0.0.0.0/0"
  excludedCIDRs:
  - "10.200.0.0/16"

  selectors:
  - namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
        - blue
        - red
        - orange

  egressGroups:
  - nodeSelector:
      matchLabels:
        node.kubernetes.io/name: k8s-wkr01
    interface: ens5

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentEgressNATPolicy
metadata:
  name: green-policy
  spec:
    egress:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - blue
          - red
          - orange
    destinationCIDRs:
    - "0.0.0.0/0"
    egressSourceIP: 192.150.9.124

# ---
# apiVersion: cilium.io/v2alpha1
# kind: CiliumBGPPeeringPolicy
# metadata:
#   name: dci
# spec:
#   nodeSelector:
#     matchLabels:
#       kubernetes.io/hostname: k8s-wkr01
#   virtualRouters:
#   - localASN: 65102
#     egressGatewayPolicySelector:
#       matchLabels:
#         advertise: bgp
#     neighbors:
#     - peerAddress: "10.0.0.5/32"
#       peerASN: 65000
#       eBGPMultihopTTL: 10
#       families:
#        - afi: ipv4
#          safi: unicast
