apiVersion: isovalent.com/v1
kind: IsovalentEgressGatewayPolicy
metadata:
  name: green-policy
  labels:
    egw: bgp-advertise
    advertise: bgp

spec:
  destinationCIDRs:
  - "0.0.0.0/0"
  excludedCIDRs:
  - "10.200.0.0/16"

  selectors:
  - namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
        - blue
        - red
        - orange

  egressGroups:
  - nodeSelector:
      matchLabels:
        node.kubernetes.io/name: k8s-wkr01
    interface: vip1
    egressIP: "192.150.9.124"

