---
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: green-policy
  spec:
    egress:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - blue
          - red
          - orange
    destinationCIDRs:
    - "0.0.0.0/0"
    egressSourceIP: 192.150.9.124