apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPAdvertisement
metadata:
  name: vip-advertisement
spec:
  nodeSelector:
    matchLabels:
      node.kubernetes.io/name: k8s-wkr01
  advertisements:
    - advertisementType: "PrefixV4"
      prefix: "192.150.9.124/30" 