apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.10.10.2:6443
    token: "9vcblo.q7hjkb66wptl0vw8"
    caCertHashes:
    - "sha256:064fb1025d67678a29fde455bc90bde64f1e9b47aa1ccb253a380d1f74250c6f"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.10.11.2,fc00:0:1001::2"