apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-alpine
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-alpine
  template:
    metadata:
      labels:
        app: test-alpine
    spec:
      containers:
        - name: test-alpine
          image: docker.io/iejalapeno/alpine:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 30; done"]
          # Ensure ping and networking tools are available
          securityContext:
            capabilities:
              add:
                - NET_RAW
                - NET_ADMIN
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m" 