apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-10-30T19:46:28Z"
  labels:
    gateway: red
    ingress: red
  name: envoy-loadbalancer-corp-svc
  namespace: heptio-contour
  resourceVersion: "123456"
  uid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 192.168.71.134
  clusterIPs:
  - 192.168.71.134
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: http
    nodePort: 30958
    port: 80
    protocol: TCP
    targetPort: 6002
  - name: https
    nodePort: 30278
    port: 443
    protocol: TCP
    targetPort: 6003
  selector:
    app: envoy
  sessionAffinity: None
  type: LoadBalancer