apiVersion: isovalent.com/v1
kind: IsovalentEgressGatewayPolicy
metadata:
  name: egress-green
  labels:
    advertise: bgp-green
spec:
  selectors:
  - podSelector:
      matchLabels:
        io.kubernetes.pod.namespace: testns
  destinationCIDRs:
  - "0.0.0.0/0"
  egressCIDRs:
  - "192.150.9.124/31"
  egressGroups:
    - nodeSelector:
        matchLabels:
          egressnode: "green"   

# Corret labels
# ➜  ciliumEgress kubectl get node -l egressnode=red
# NAME                                          STATUS   ROLES    AGE   VERSION
# cpt-worker-ethos11devut1-91.ethos.adobe.net   Ready    worker   24d   v1.29.6
# cpt-worker-ethos11devut1-92.ethos.adobe.net   Ready    worker   24d   v1.29.6
# ➜  ciliumEgress kubectl get node -l egressnode=green
# NAME                                          STATUS   ROLES    AGE   VERSION
# cpt-worker-ethos11devut1-96.ethos.adobe.net   Ready    worker   24d   v1.29.6
# cpt-worker-ethos11devut1-97.ethos.adobe.net   Ready    worker   24d   v1.29.6
# ➜  ciliumEgress kubectl get node -l egressnode=blue 
# NAME                                          STATUS   ROLES    AGE   VERSION
# cpt-worker-ethos11devut1-94.ethos.adobe.net   Ready    worker   24d   v1.29.6
# cpt-worker-ethos11devut1-95.ethos.adobe.net   Ready    worker   24d   v1.29.6
