apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPAdvertisement
metadata:
  name: green
  labels:
    ingress: bgp-green
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: advertise, operator: In, values: [ bgp-green ] }
      attributes:
        communities:
          standard: 
          - 64512:5
          - 65000:1730
          - 65000:5006
          - 65009:9003
