
---
kind: Namespace
apiVersion: v1
metadata:
  name: testns
  labels:
    name: testns

---
kind: Namespace
apiVersion: v1
metadata:
  name: testns2
  labels:
    name: testns2

---
apiVersion: v1
kind: Pod
metadata:
  namespace: testns
  labels:
    app: alpine-ping
  name: testpod0
spec:
  containers:
  - image: iejalapeno/alpine:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    name: testpod0
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"

---
apiVersion: v1
kind: Pod
metadata:
  namespace: testns2
  labels:
    app: alpine-ping
  name: testpod1
spec:
  containers:
  - image: alpine:latest
    imagePullPolicy: IfNotPresent
    name: testpod1
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"


