MTU: 1500
agentNotReadyTaintKey: CiliumIsDown
bpf:
  masquerade: true
debug:
  enabled: true
  verbose: flow,datapath,envoy,policy
ipv6:
  enabled: true
egressGateway:
  enabled: true
  installRoutes: true
enterprise:
  featureGate:
    approved:
    - EnterpriseBGPControlPlane
    - EgressGatewayHA
    - EgressGatewayIPv4
  egressGatewayHA:
    enabled: true 
  bgpControlPlane:
    enabled: true
envoy:
  enabled: true
hubble:
  enabled: false
  relay:
    enabled: false
nodePort:
  enabled: true
nodeinit:
  enabled: true
gatewayAPI:
  enabled: true
kubeProxyReplacement: "true"
k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: true
ipam:
  #mode: kubernetes
  mode: "cluster-pool"
  ciliumNodeUpdateRate: "15s"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.200.0.0/16"]
