apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: green-egress
spec:
  nodeSelector:
    matchLabels:
      egress-node: green
  virtualRouters:
  - egressGatewayPolicySelector:
      matchLabels:
        advertise: bgp-green
    exportPodCIDR: false
    localASN: 65010
    neighbors:
    - advertisedPathAttributes:
      - communities:
          standard:
          - "64512:5"
          - 65000:1730
          - 65000:5006
          - 65009:9003
        selector:
          matchLabels:
            advertise: bgp-green
        selectorType: IsovalentEgressGatewayPolicy
      connectRetryTimeSeconds: 120
      eBGPMultihopTTL: 5
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      peerASN: 65005
      peerAddress: 10.0.0.5/32
      peerPort: 179

