apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPAdvertisement
metadata:
  name: green
  labels:
    ingress: bgp-green
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: ingress, operator: In, values: [ bgp-green ] }
      attributes:
        communities:
          standard: 
          - 64512:5
          - 65000:1730
          - 65000:5006
          - 65009:9003

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPAdvertisement
metadata:
  name: blue
  labels:
    ingress: bgp-blue
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: ingress, operator: In, values: [ bgp-blue ] }
      attributes:
        communities:
          standard: 
          - 64512:1
          - 65000:1720
          - 65000:5006
          - 65004:9001

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPAdvertisement
metadata:
  name: red
  labels:
    ingress: bgp-red
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: ingress, operator: In, values: [ bgp-red ] }
      attributes:
        communities:
          standard: 
          - 64512:1
          - 65000:1720
          - 65000:5006
          - 65004:9112