# operator commented out - this one works

MTU: 1500
agentNotReadyTaintKey: CiliumIsDown
bpf:
  masquerade: true
debug:
  enabled: true
  verbose: flow,datapath,envoy,policy
ipv6:
  enabled: true
egressGateway:
  enabled: true
  installRoutes: true
enterprise:
  featureGate:
    approved:
    - EnterpriseBGPControlPlane
    - EgressGatewayHA
    - EgressGatewayIPv4
  egressGatewayHA:
    enabled: true
    healthcheckTimeout: 1s
    socketTermination:
      enabled: true
  bgpControlPlane:
    enabled: true
envoy:
  enabled: true
  extraArgs:
  - --component-log-level http:debug,http2:debug,filter:debug,conn_handler:debug,router:debug,connection:debug,upstream:debug,pool:debug
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
hubble:
  enabled: true
  metrics:
    dashboards:
      annotations:
        grafana_folder: Hubble
      enabled: true
      namespace: kube-system
    enableOpenMetrics: true
    enabled:
    - tcp
    - icmp
    - policy
    - dns:query;ignoreAAAA;labelsContext=source_namespace,source_workload,destination_namespace,destination_workload;sourceContext=workload-name|pod-name|dns|reserved-identity;destinationContext=workload-name|pod-name|dns|reserved-identity
    - drop:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload;sourceContext=workload-name|pod-name|dns|reserved-identity;destinationContext=workload-name|pod-name|dns|reserved-identity
    - flow:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload;sourceContext=workload-name|pod-name|dns|reserved-identity;destinationContext=workload-name|pod-name|dns|reserved-identity
    - flows-to-world:labelsContext=source_namespace,source_workload;sourceContext=workload-name|pod-name|dns|reserved-identity
    - httpV2:exemplars=true;labelsContext=source_namespace,source_workload,source_app,destination_namespace,destination_workload,destination_app,traffic_direction;sourceContext=workload-name|pod-name|dns|reserved-identity;destinationContext=workload-name|pod-name|dns|reserved-identity
    serviceMonitor:
      enabled: true
  relay:
    dialTimeout: 15s
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    retryTimeout: 15s
nodePort:
  enabled: true
nodeinit:
  enabled: true
gatewayAPI:
  enabled: true
kubeProxyReplacement: "true"
k8s:
  requireIPv4PodCIDR: true
ipam:
  mode: "cluster-pool"
  ciliumNodeUpdateRate: "15s"
  operator:
    clusterPoolIPv4PodCIDRList: ["172.16.0.0/16"]
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true


