apiVersion: v1
items:
- apiVersion: cilium.io/v2alpha1
  kind: CiliumLoadBalancerIPPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cilium.io/v2alpha1","kind":"CiliumLoadBalancerIPPool","metadata":{"annotations":{},"labels":{"ingress":"bgp-blue"},"name":"blue"},"spec":{"blocks":[{"cidr":"10.27.248.13/31"}],"serviceSelector":{"matchLabels":{"gateway":"blue"}}}}
    creationTimestamp: "2025-05-08T19:05:18Z"
    generation: 1
    labels:
      ingress: bgp-blue
    name: blue
    resourceVersion: "38266469"
    uid: 06e6e00b-6cc1-461a-9acd-4d13e6f07616
  spec:
    blocks:
    - cidr: 10.27.248.13/31
    disabled: false
    serviceSelector:
      matchLabels:
        gateway: blue
  status:
    conditions:
    - lastTransitionTime: "2025-05-08T19:05:48Z"
      message: ""
      observedGeneration: 1
      reason: resolved
      status: "False"
      type: cilium.io/PoolConflict
    - lastTransitionTime: "2025-05-08T19:05:48Z"
      message: "2"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsTotal
    - lastTransitionTime: "2025-05-08T19:05:49Z"
      message: "1"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsAvailable
    - lastTransitionTime: "2025-05-08T19:05:49Z"
      message: "1"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsUsed
- apiVersion: cilium.io/v2alpha1
  kind: CiliumLoadBalancerIPPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cilium.io/v2alpha1","kind":"CiliumLoadBalancerIPPool","metadata":{"annotations":{},"labels":{"ingress":"bgp-green"},"name":"green"},"spec":{"blocks":[{"cidr":"192.150.9.126/31"}],"serviceSelector":{"matchLabels":{"gateway":"green"}}}}
    creationTimestamp: "2025-05-08T19:05:18Z"
    generation: 1
    labels:
      ingress: bgp-green
    name: green
    resourceVersion: "38266472"
    uid: b8136085-b5cf-4734-856a-0de8050f85d5
  spec:
    blocks:
    - cidr: 192.150.9.126/31
    disabled: false
    serviceSelector:
      matchLabels:
        gateway: green
  status:
    conditions:
    - lastTransitionTime: "2025-05-08T19:05:48Z"
      message: ""
      observedGeneration: 1
      reason: resolved
      status: "False"
      type: cilium.io/PoolConflict
    - lastTransitionTime: "2025-05-08T19:05:48Z"
      message: "2"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsTotal
    - lastTransitionTime: "2025-05-08T19:05:48Z"
      message: "1"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsAvailable
    - lastTransitionTime: "2025-05-08T19:05:49Z"
      message: "1"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsUsed
- apiVersion: cilium.io/v2alpha1
  kind: CiliumLoadBalancerIPPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cilium.io/v2alpha1","kind":"CiliumLoadBalancerIPPool","metadata":{"annotations":{},"labels":{"ingress":"red"},"name":"red"},"spec":{"blocks":[{"cidr":"10.27.248.29/31"}],"serviceSelector":{"matchLabels":{"gateway":"red"}}}}
    creationTimestamp: "2025-05-08T19:05:19Z"
    generation: 1
    labels:
      ingress: red
    name: red
    resourceVersion: "38266468"
    uid: b5c8574d-8048-4420-b2f0-e7a1fcc55eb5
  spec:
    blocks:
    - cidr: 10.27.248.29/31
    disabled: false
    serviceSelector:
      matchLabels:
        gateway: red
  status:
    conditions:
    - lastTransitionTime: "2025-05-08T19:05:49Z"
      message: ""
      observedGeneration: 1
      reason: resolved
      status: "False"
      type: cilium.io/PoolConflict
    - lastTransitionTime: "2025-05-08T19:05:49Z"
      message: "2"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsTotal
    - lastTransitionTime: "2025-05-08T19:05:49Z"
      message: "1"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsAvailable
    - lastTransitionTime: "2025-05-08T19:05:49Z"
      message: "1"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsUsed
kind: List
metadata:
  resourceVersion: ""
