apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: cluster00-cp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: cluster00-cp
  virtualRouters:
  - localASN: 65009
    exportPodCIDR: true
    neighbors:
    - peerAddress: "10.10.10.1/32"
      peerASN: 65002
      families:
       - afi: ipv4
         safi: unicast

---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: green-egress
spec:
  nodeSelector:
    matchLabels:
      egressnode: "green"
  virtualRouters:
  - localASN: 65010
    egressGatewayPolicySelector:
      matchLabels:
        advertise: bgp-green
    neighbors:
    - peerAddress: '10.0.0.99/32'
      eBGPMultihopTTL: 5
      peerASN: 65005
      advertisedPathAttributes:
      - selectorType: IsovalentEgressGatewayPolicy
        selector:
          matchLabels:
            advertise: bgp-green
    - peerAddress: "10.10.11.1/32"
      peerASN: 65003
      families:
       - afi: ipv4
         safi: unicast