apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"envoy-corp"},"name":"contour-corp-envoy-metrics-svc","namespace":"heptio-contour"},"spec":{"clusterIP":"None","ports":[{"name":"http-metrics","port":8524,"protocol":"TCP"}],"selector":{"app":"envoy","envoy":"corp"},"type":"ClusterIP"}}
    creationTimestamp: "2025-03-31T20:57:39Z"
    labels:
      k8s-app: envoy-corp
    name: contour-corp-envoy-metrics-svc
    namespace: heptio-contour
    resourceVersion: "797983"
    uid: 343faf06-3f81-49a4-81de-c8073d54eade
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 8524
      protocol: TCP
      targetPort: 8524
    selector:
      app: envoy
      envoy: corp
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"contour-corp-svc","namespace":"heptio-contour"},"spec":{"clusterIP":"None","ports":[{"name":"xds","port":8500,"protocol":"TCP","targetPort":8500},{"name":"metrics","port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"contour-corp"},"type":"ClusterIP"}}
    creationTimestamp: "2025-03-31T20:57:39Z"
    name: contour-corp-svc
    namespace: heptio-contour
    resourceVersion: "797980"
    uid: 3a0cd163-19ae-47f4-a94c-629b5df115b4
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: xds
      port: 8500
      protocol: TCP
      targetPort: 8500
    - name: metrics
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: contour-corp
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"envoy-internal"},"name":"contour-internal-envoy-metrics-svc","namespace":"heptio-contour"},"spec":{"clusterIP":"None","ports":[{"name":"http-metrics","port":8544,"protocol":"TCP"}],"selector":{"app":"envoy","envoy":"internal"},"type":"ClusterIP"}}
    creationTimestamp: "2025-03-31T20:57:40Z"
    labels:
      k8s-app: envoy-internal
    name: contour-internal-envoy-metrics-svc
    namespace: heptio-contour
    resourceVersion: "797991"
    uid: 3aff6353-0453-4ef0-a7c2-c2d6326d4339
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 8544
      protocol: TCP
      targetPort: 8544
    selector:
      app: envoy
      envoy: internal
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"contour-internal-svc","namespace":"heptio-contour"},"spec":{"clusterIP":"None","ports":[{"name":"xds","port":8500,"protocol":"TCP","targetPort":8500},{"name":"metrics","port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"contour-internal"},"type":"ClusterIP"}}
    creationTimestamp: "2025-03-31T20:57:40Z"
    name: contour-internal-svc
    namespace: heptio-contour
    resourceVersion: "797988"
    uid: 09d3b873-a817-461d-b41c-dda3bab23dc0
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: xds
      port: 8500
      protocol: TCP
      targetPort: 8500
    - name: metrics
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: contour-internal
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"envoy-public"},"name":"contour-public-envoy-metrics-svc","namespace":"heptio-contour"},"spec":{"clusterIP":"None","ports":[{"name":"http-metrics","port":8504,"protocol":"TCP"}],"selector":{"app":"envoy","envoy":"public"},"type":"ClusterIP"}}
    creationTimestamp: "2025-03-31T20:57:40Z"
    labels:
      k8s-app: envoy-public
    name: contour-public-envoy-metrics-svc
    namespace: heptio-contour
    resourceVersion: "797999"
    uid: dbfdc004-d864-457f-807b-928db4581ae0
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 8504
      protocol: TCP
      targetPort: 8504
    selector:
      app: envoy
      envoy: public
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"contour-public-svc","namespace":"heptio-contour"},"spec":{"clusterIP":"None","ports":[{"name":"xds","port":8500,"protocol":"TCP","targetPort":8500},{"name":"metrics","port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"contour-public"},"type":"ClusterIP"}}
    creationTimestamp: "2025-03-31T20:57:40Z"
    name: contour-public-svc
    namespace: heptio-contour
    resourceVersion: "797995"
    uid: f2857cb8-9e63-4863-911e-a0ac752df36f
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: xds
      port: 8500
      protocol: TCP
      targetPort: 8500
    - name: metrics
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: contour-public
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2024-10-30T19:46:28Z","labels":{"gateway":"red","ingress":"red"},"name":"envoy-loadbalancer-corp-svc","namespace":"heptio-contour","resourceVersion":"123456","uid":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"192.168.71.134","clusterIPs":["192.168.71.134"],"externalTrafficPolicy":"Local","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","loadBalancerSourceRanges":["0.0.0.0/0"],"ports":[{"name":"http","nodePort":30958,"port":80,"protocol":"TCP","targetPort":6002},{"name":"https","nodePort":30278,"port":443,"protocol":"TCP","targetPort":6003}],"selector":{"app":"envoy"},"sessionAffinity":"None","type":"LoadBalancer"}}
    creationTimestamp: "2025-04-01T16:36:38Z"
    labels:
      gateway: red
      ingress: red
    name: envoy-loadbalancer-corp-svc
    namespace: heptio-contour
    resourceVersion: "37189762"
    uid: 175fafe8-7235-4bab-8317-7a5e6e7c470c
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 192.168.71.134
    clusterIPs:
    - 192.168.71.134
    externalTrafficPolicy: Local
    healthCheckNodePort: 32560
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    loadBalancerSourceRanges:
    - 0.0.0.0/0
    ports:
    - name: http
      nodePort: 30958
      port: 80
      protocol: TCP
      targetPort: 6002
    - name: https
      nodePort: 30278
      port: 443
      protocol: TCP
      targetPort: 6003
    selector:
      app: envoy
    sessionAffinity: None
    type: LoadBalancer
  status:
    conditions:
    - lastTransitionTime: "2025-05-08T19:05:49Z"
      message: ""
      reason: satisfied
      status: "True"
      type: cilium.io/IPAMRequestSatisfied
    loadBalancer:
      ingress:
      - ip: 10.27.248.28
        ipMode: VIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"gateway":"blue","ingress":"blue"},"name":"envoy-loadbalancer-internal-svc","namespace":"heptio-contour","resourceVersion":"7889","uid":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"192.168.141.148","clusterIPs":["192.168.141.148"],"externalTrafficPolicy":"Local","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","loadBalancerSourceRanges":["0.0.0.0/0"],"ports":[{"name":"http","nodePort":30742,"port":80,"protocol":"TCP","targetPort":6004},{"name":"https","nodePort":32300,"port":443,"protocol":"TCP","targetPort":6005}],"selector":{"app":"envoy"},"sessionAffinity":"None","type":"LoadBalancer"}}
    creationTimestamp: "2025-04-01T16:36:50Z"
    labels:
      gateway: blue
      ingress: blue
    name: envoy-loadbalancer-internal-svc
    namespace: heptio-contour
    resourceVersion: "37192729"
    uid: 97b49f23-92c3-4aa1-b0a3-c9c0a1fcfba8
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 192.168.141.148
    clusterIPs:
    - 192.168.141.148
    externalTrafficPolicy: Local
    healthCheckNodePort: 30118
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    loadBalancerSourceRanges:
    - 0.0.0.0/0
    ports:
    - name: http
      nodePort: 30742
      port: 80
      protocol: TCP
      targetPort: 6004
    - name: https
      nodePort: 32300
      port: 443
      protocol: TCP
      targetPort: 6005
    selector:
      app: envoy
    sessionAffinity: None
    type: LoadBalancer
  status:
    conditions:
    - lastTransitionTime: "2025-05-08T19:05:48Z"
      message: ""
      reason: satisfied
      status: "True"
      type: cilium.io/IPAMRequestSatisfied
    loadBalancer:
      ingress:
      - ip: 10.27.248.12
        ipMode: VIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"gateway":"green","ingress":"green"},"name":"envoy-loadbalancer-public-svc","namespace":"heptio-contour","resourceVersion":"78987","uid":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"192.168.158.134","clusterIPs":["192.168.158.134"],"externalTrafficPolicy":"Local","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","loadBalancerSourceRanges":["0.0.0.0/0"],"ports":[{"name":"http","nodePort":30819,"port":80,"protocol":"TCP","targetPort":6000},{"name":"https","nodePort":32690,"port":443,"protocol":"TCP","targetPort":6001}],"selector":{"app":"envoy"},"sessionAffinity":"None","type":"LoadBalancer"}}
    creationTimestamp: "2025-04-01T16:36:57Z"
    labels:
      gateway: green
      ingress: green
    name: envoy-loadbalancer-public-svc
    namespace: heptio-contour
    resourceVersion: "37193119"
    uid: e910f5e9-3963-454e-9ca7-050dcf127fa9
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 192.168.158.134
    clusterIPs:
    - 192.168.158.134
    externalTrafficPolicy: Local
    healthCheckNodePort: 31792
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    loadBalancerSourceRanges:
    - 0.0.0.0/0
    ports:
    - name: http
      nodePort: 30819
      port: 80
      protocol: TCP
      targetPort: 6000
    - name: https
      nodePort: 32690
      port: 443
      protocol: TCP
      targetPort: 6001
    selector:
      app: envoy
    sessionAffinity: None
    type: LoadBalancer
  status:
    conditions:
    - lastTransitionTime: "2025-05-08T19:05:48Z"
      message: ""
      reason: satisfied
      status: "True"
      type: cilium.io/IPAMRequestSatisfied
    loadBalancer:
      ingress:
      - ip: 192.150.9.126
        ipMode: VIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"envoy"},"name":"envoy-stats","namespace":"heptio-contour"},"spec":{"clusterIP":"None","ports":[{"name":"stats","port":4001,"protocol":"TCP","targetPort":"stats"}],"selector":{"app":"envoy"},"type":"ClusterIP"}}
    creationTimestamp: "2025-03-31T21:00:37Z"
    labels:
      k8s-app: envoy
    name: envoy-stats
    namespace: heptio-contour
    resourceVersion: "805926"
    uid: 76285745-7b0f-449c-bad3-0226f5c2f4c7
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: stats
      port: 4001
      protocol: TCP
      targetPort: stats
    selector:
      app: envoy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"kapcom","namespace":"heptio-contour"},"spec":{"clusterIP":"None","ports":[{"name":"xds","port":3000,"protocol":"TCP","targetPort":3000},{"name":"http","port":3001,"protocol":"TCP","targetPort":3001}],"selector":{"app":"kapcom"},"type":"ClusterIP"}}
    creationTimestamp: "2025-03-31T20:57:42Z"
    name: kapcom
    namespace: heptio-contour
    resourceVersion: "798036"
    uid: 7a975b2c-a401-40d4-ba2e-6048123319b4
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: xds
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: http
      port: 3001
      protocol: TCP
      targetPort: 3001
    selector:
      app: kapcom
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
