apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "green"
  labels:
    ingress: bgp-green
spec:
  blocks:
  - cidr: "192.150.9.126/31"
  serviceSelector:
    matchLabels:
      gateway: green


