loadBalancer:
  mode: maglev
  # Add ingress load balancer configuration
  ingress:
    enabled: true
    nodeSelector:
      matchLabels:
        ingressnode: blue 
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
image:
  tag: v1.16.8-cee.4 