apiVersion: v1
kind: Service
metadata:
  name: test-service-snat
  annotations:
    service.cilium.io/loadbalancer-mode: "snat"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: test-app