apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: cluster00-wkr00
spec:
  nodeSelector:
    matchLabels:
      egress-node: "green"
  bgpInstances:
  - name: "instance-65010"
    localASN: 65010
    peers:
    - name: "r05"
      peerASN: 65005
      peerAddress: 10.0.0.5
      peerConfigRef:
        name: "cilium-peer"



