apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPAdvertisement
metadata:
  name: bgp-green
  labels:
    advertise: bgp-green
spec:
  advertisements:
    - advertisementType: "EgressGateway"
      selector:            
        matchExpressions:
          - { key: advertise, operator: In, values: [ bgp-green ] }
