apiVersion: isovalent.com/v1
kind: IsovalentEgressGatewayPolicy
metadata:
  name: egress-green
  labels:
    advertise: bgp-green

spec:
  selectors:
  - podSelector:
      matchLabels:
        io.kubernetes.pod.namespace: blue
  destinationCIDRs:
  - "0.0.0.0/0"
  egressCIDRs:
  - "192.150.9.124/31"
  egressGroups:
    - nodeSelector:
        matchLabels:
          egress-node: "green"   
