# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumBGPPeeringPolicy
# metadata:
#   name: green-egress
# spec:
#   nodeSelector:
#     matchLabels:
#       egressnode: "green"
#   virtualRouters:
#   - localASN: 65010
#     egressGatewayPolicySelector:
#       matchLabels:
#         advertise: bgp-green
#     neighbors:
#     - peerAddress: '10.0.0.99/32'
#       eBGPMultihopTTL: 5
#       peerASN: 65005
#       advertisedPathAttributes:
#       - selectorType: IsovalentEgressGatewayPolicy
#         selector:
#           matchLabels:
#             advertise: bgp-green

---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: green-egress
spec:
  nodeSelector:
    matchLabels:
      egressnode: "green"
  virtualRouters:
  - localASN: 65010
    egressGatewayPolicySelector:
      matchLabels:
        advertise: bgp-green
    neighbors:
    - peerAddress: '10.0.0.99/32'
      eBGPMultihopTTL: 5
      peerASN: 65005
      advertisedPathAttributes:
      - selectorType: IsovalentEgressGatewayPolicy
        selector:
          matchLabels:
            advertise: bgp-green