apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: green-egress
spec:
  nodeSelector:
    matchLabels:
      egress-node: "green"
  bgpInstances:
  - name: "instance-green"
    localASN: 65010
    peers:
    - name: "DCI"
      peerASN: 65005
      peerAddress: 10.0.0.5
      peerConfigRef:
        name: "cilium-peer"



